online/online/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("website/", include("website.urls")),
                  path("users/", include("users.urls")),
                  path("booking/", include("booking.urls")),
                  path("__debug__/", include("debug_toolbar.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online/users/urls.py
from django.urls import path

from . import views
from .views import MyPasswordResetView, PasswordResetConfirmView

"""
Основные маршруты приложения users.
"""

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("password-change/", views.password_change, name="password-change"),
    path("activate/<str:uidb64>/<str:token>/", views.activate, name="activate"),
    path("password_reset/", MyPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", views.password_reset_done, name="password_reset_done"),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        views.password_reset_complete,
        name="password_reset_complete",
    ),
]

online/website/urls.py
from django.urls import path

from . import views

"""
Основные маршруты приложения website.
"""

app_name = "website"
urlpatterns = [
    path("", views.index, name="index"),
    path("profile", views.profile, name="profile"),
    path("profile_edit", views.profile_edit, name="profile_edit"),
    path("service", views.service_view, name="service"),
    path("contact", views.contact, name="contact"),
    path("service/<int:pk>", views.service_info, name="service_info"),
    path("comment", views.comments, name="comment"),
    path("comment_add", views.comment_add, name="comment_add"),
    path(
        "comment/<int:pk>/update",
        views.CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "comment/<int:pk>/delete",
        views.CommentDeleteView.as_view(),
        name="comment-delete",
    ),
    path("gallery", views.gallery, name="photo-gallery"),
]

online/users/models.py
from django.db import models

# Create your models here.

online/users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import ValidationError
from django.urls import reverse_lazy


class CustomUserCreationForm(UserCreationForm):
    """
    Форма создания пользователя
    """

    email = forms.EmailField(
        max_length=254,
        required=True,
        widget=forms.EmailInput(attrs={"size": "65", "style": "height: 60px;"}),
    )
    username = forms.CharField(
        label="Введите никнейм",
        widget=forms.TextInput(attrs={"class": "my-input"}),
        help_text="Никнейм не должен содержать специальные символы",
    )
    password1 = forms.CharField(
        label="Введите пароль",
        widget=forms.PasswordInput(attrs={"class": "my-input"}),
        help_text="Ваш пароль не может состоять полностью из цирф и должен содержать не менее 8 символов",
    )
    password2 = forms.CharField(
        label="Повторите пароль",
        widget=forms.PasswordInput(attrs={"class": "my-input"}),
    )

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + (
            "email",
            "password1",
            "password2",
        )

    def clean_email(self):
        """
        Форма для ввода данных профиля
        """
        email = self.cleaned_data.get("email")
        if email and User.objects.filter(email=email).exists():
            raise ValidationError("This email address is already in use.")
        return email


class LoginForm(forms.Form):
    """
    Форма для входа в аккаунт
    """

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CustomPasswordChangeForm(PasswordChangeForm):
    """
    Создал кастомную форму для добавления функционала смены пароля
    """

    template_name = "users/password_change.html"
    success_url = reverse_lazy("users:success_change")

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

        for fieldname in ["old_password", "new_password1", "new_password2"]:
            self.fields[fieldname].help_text = None

    def clean(self):
        """
        при совпадении нового пароля со старым выскакивает ошибка
        """
        cleaned_data = super().clean()
        user = self.user
        new = cleaned_data.get("new_password1")
        if user.check_password(new):
            raise ValidationError("Новый пароль совпадает со старым")

online/users/views.py
import os

from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.views import (PasswordResetConfirmView,
                                       PasswordResetView)
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from dotenv import load_dotenv

from .forms import CustomPasswordChangeForm, CustomUserCreationForm, LoginForm
from .tasks import register_message
from .token import account_activation_token

load_dotenv()


def register(request: HttpRequest) -> HttpResponse:
    """
    Отображает форму регистрации пользователя

    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP с формой на странице
    """
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            message = render_to_string(
                "activate_email.html",
                {
                    "user": user,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": account_activation_token.make_token(user),
                },
            )
            to_email = form.cleaned_data.get("email")
            register_message.delay(message, to_email)
            return render(request, "users/confirm_email.html")
    else:
        form = CustomUserCreationForm()
    return render(request, "users/register.html", {"form": form})


def activate(request: HttpRequest, uidb64: str, token: str) -> HttpResponse:
    """
    Активация токена регистрации

    Args:
        request (HttpRequest): объект запроса HTTP
        uidb64 (str): это строка, содержащая 64-битное представление значения целого числа.
        token (str): уникальный токен аутентификации

    Returns:
        HttpResponse: объект ответа HTTP со страницей профиля пользователя и форму для заполнения профиля.
    """

    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect(reverse("website:profile"))
    else:
        return render(request, "users/false_email_token.html")


def login_view(request: HttpRequest) -> HttpResponse:
    """
    Отображает форму входа в аккаунт

    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP с формой логина на странице
    """
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd["username"], password=cd["password"])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(reverse("website:index"))
                else:
                    return render(request, "users/disabled_acc.html")
            else:
                return render(request, "users/invalid_login.html")
    else:
        form = LoginForm()
    return render(request, "users/login.html", {"form": form})


def logout_view(request: HttpRequest) -> HttpResponse:
    """
    Выход из аккаунта
    """
    logout(request)
    return redirect("website:index")


def password_change(request: HttpRequest) -> HttpResponse:
    """
    Отображает форму изменения пароля

    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP с формой отображения изменения пароля
    """
    if request.method == "POST":
        form = CustomPasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return render(request, "users/password_change_success.html")
    else:
        current_user = request.user
        form = CustomPasswordChangeForm(current_user)
    return render(request, "users/password_change.html", {"form": form})


class MyPasswordResetView(PasswordResetView):
    """Класс для сброса пароля пользователя."""

    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    from_email = os.environ.get("EMAIL_HOST_USER")
    success_url = reverse_lazy("users:password_reset_done")

    def form_valid(self, form):
        """
        Проверяет, существует ли email-адрес в базе данных и отправляет письмо с инструкцией по сбросу пароля.
        """
        email = form.cleaned_data.get("email")
        user = User.objects.filter(
            email=email
        ).first()  # Используем filter и first вместо get с аргументом default=None
        if not user:
            return render(self.request, "users/reset_email_false.html")
        return super().form_valid(form)


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    """Класс для подтверждения сброса пароля пользователя."""

    template_name = "users/password_reset_confirm.html"
    success_url = reverse_lazy("users:password_reset_complete")


def password_reset_done(request: HttpRequest) -> HttpResponse:
    """
    Отображает страницу с подтвеждением отправки сообщения на почту

    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP с формой отображения изменения пароля
    """
    context = {
        "message": "Сброс пароля успешно выполнен! Проверьте почту на наличие письма подтверждение изменения пароля",
    }
    return render(request, "users/password_reset_done.html", context)


def password_reset_complete(request: HttpRequest) -> HttpResponse:
    """
    Отображает страницу с подтвеждением изменения пароля

    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP с формой отображения изменения пароля
    """
    context = {
        "message": "Ваш пароль изменен",  # Сообщение, которое вы хотите отобразить на странице
    }
    return render(request, "users/password_reset_complete.html", context)

online/users/templates/users/confirm_email.html
{% extends "base.html"%}
{% load static %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-6 text-center">
      <i class="fa fa-envelope" aria-hidden="true"></i>
      <h2 class="confirm">Спасибо за регистрацию!</h2>
      <p class="lead mb-5">На ваш почтовый адрес отправлена ссылка подтверждения, для активации аккаунта</p>
      <a class="btn btn-primary btn-lg" href="{%url 'website:index' %}" role="button">Вернуться на главную страницу</a>
    </div>
  </div>
</div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/disabled_acc.html
{% extends "base.html"%}
{% load static %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-6 text-center">
      <i class="fa fa-envelope" aria-hidden="true"></i>
      <h2 class="confirm">Аккаунт не активирован</h2>
      <p class="lead mb-5">Для активации аккаунта перейдите по ссылке, которая была отправлена на ваш почтовый адрес</p>
      <a class="btn btn-primary btn-lg" href="{% url 'website:index' %}" role="button">Вернуться на главную страницу</a>
    </div>
  </div>
</div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/false_email_token.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center align-items-center">
      <div class="col-md-6 text-center">
        <i class="fa fa-exclamation-triangle fa-4x text-danger mb-3"></i>
        <h2 class="confirm">Ваш токен оказался недействительным</h2>
        <p class="lead mb-5">Попробуйте еще раз</p>
        <a class="btn btn-primary btn-lg" href="{% url 'website:index' %}" role="button">Перейти на главную</a>
      </div>
    </div>
  </div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/invalid_login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center align-items-center">
      <div class="col-md-6 text-center">
        <i class="fa fa-exclamation-triangle fa-4x text-danger mb-3"></i>
        <h2 class="confirm">Неправильно введен логин или пароль</h2>
        <a class="btn btn-primary mr-3" href="{% url 'users:login' %}" role="button">Попробовать снова</a>
        <a class="btn btn-primary mr-3" href="{% url 'website:index' %}" role="button">Вернуться на главную</a>
      </div>
    </div>
  </div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="login">
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Войти" class="btn-login btn-primary">
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <a href="{% url 'users:register' %}" class="btn-login btn-primary">Зарегистрироваться</a>
    </form>

    <a class="button-login" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
    <a class="button-login" href="{% url 'website:index' %}" style="float: right;">Вернуться на главную</a>
</div>
{% endblock %}
{% include "footer.html" %}

online/users/templates/users/password_change.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="password-change">
    <h2>Change password</h2>
    <form method="post">
        {% csrf_token %}
            <div class="form-group-password">
                {{ form.as_p }}
            </div>
        <input type="submit" value="Изменить пароль" class="btn-login btn-primary">
    </form>
    <a href="{% url 'website:index' %}" class="button-login" style="display: block; width: 100%; text-align: center;">Вернуться на главную</a>

</div>
{% endblock %}
{% include "footer.html" %}

online/users/templates/users/password_change_success.html
{% extends "base.html"%}
{% load static %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-6 text-center">
        <i class="fas fa-key fa-4x"></i>
        <h2 class="confirm">Изменение пароля прошло успешно</h2>
        <a class="btn btn-primary btn-lg" href="{%url 'website:index' %}" role="button">Вернуться на главную страницу</a>
    </div>
  </div>
</div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6 text-center">
        <h3 class="mb-4">Пароль был успешно изменен</h3>
        <a href="{% url 'users:login' %}" class="btn btn-primary mr-3">Вернуться на вход</a>
        <a href="{% url 'website:index' %}" class="btn btn-primary">Вернуться на главную</a>
      </div>
    </div>
  </div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">
            <form method="post">{% csrf_token %}
                <fieldset class="module aligned">
                    <div class="form-row field-password1">
                        {{ form.new_password1.errors }}
                        <label for="id_new_password1">Введите новый пароль</label>
                        {{ form.new_password1 }}
                    </div>
                    <div class="form-row field-password2">
                        {{ form.new_password2.errors }}
                        <label for="id_new_password2">Подтвердите новый пароль</label>
                        {{ form.new_password2 }}
                    </div>
                    <input type="submit" value='Подтвердить' class="btn btn-primary mr-3">
                </fieldset>
            </form>
            <a href="{% url 'users:login' %}" class="btn btn-primary mr-3">Вернуться на вход</a>
            <a href="{% url 'website:index' %}" class="btn btn-primary">Вернуться на главную</a>
        </div>
    </div>
</div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6 text-center">
            <div class="done-container">
                <h3 class="done">{{ message }}</h3>
            </div>
            <a class="btn btn-primary mr-3" href="{%url 'website:index' %}">Вернуться на главную</a>
        </div>
    </div>
</div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/password_reset_email.html
Привет {{ user.username }},

Вы получили это письмо, потому что запросили сброс пароля на сайте {{ site_name }}.

Пожалуйста, перейдите по следующей ссылке, чтобы сбросить ваш пароль:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Если вы не запрашивали сброс пароля, проигнорируйте это сообщение.

С уважением,
Команда сайта {{ site_name }}

online/users/templates/users/password_reset_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="email_form">
    <h2 class="email_form">Change password</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group-email_form">
            {{ form.email.errors }}
            <p class="email_form">Введите почту:</p>
            {{ form.email }}
        </div>
        <input type="submit" value="Восстановить пароль">
    </form>
</div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="login">
    <h2>Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Зарегистрироваться" class="btn-login btn-primary">
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    </form>

    <a class="button-login" href="{% url 'users:login' %}">Вернуться к Login</a>
    <a class="button-login" href="{% url 'website:index' %}" style="float: right;">Вернуться на главную</a>
</div>
{% endblock %}

{% include "footer.html" %}

online/users/templates/users/reset_email_false.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6 text-center">
            <i class="fa fa-envelope" aria-hidden="true"></i>
            <h2 class="confirm">Такой почты не существует</h2>
            <a class="btn btn-primary btn-lg mb-5" href="{% url 'users:password_reset' %}" role="button">Вернуться ко
                вводу почты</a>
        </div>
    </div>
</div>
{% endblock %}

{% include "footer.html" %}