online/booking/urls.py
from django.urls import path

from . import views

"""
Основные маршруты приложения booking.
"""

app_name = "booking"
urlpatterns = [
    path("booking", views.booking, name="booking"),
    path("booking_day", views.booking_day, name="booking_day"),
    path("booking_day/<int:service_id>", views.booking_day, name="booking_day"),
    path("booking-submit", views.bookingsubmit, name="bookingSubmit"),
    path("user-update/<int:id>", views.userupdate, name="userUpdate"),
    path(
        "user-update-submit/<int:id>", views.userupdatesubmit, name="userUpdateSubmit"
    ),
    path("remove/<int:id>", views.remove, name="remove"),
    path("user_record", views.record_view, name="user_record"),
    path("history", views.history_user, name="history_user"),
]

online/online/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("website/", include("website.urls")),
                  path("users/", include("users.urls")),
                  path("booking/", include("booking.urls")),
                  path("__debug__/", include("debug_toolbar.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online/users/urls.py
from django.urls import path

from . import views
from .views import MyPasswordResetView, PasswordResetConfirmView

"""
Основные маршруты приложения users.
"""

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("password-change/", views.password_change, name="password-change"),
    path("activate/<str:uidb64>/<str:token>/", views.activate, name="activate"),
    path("password_reset/", MyPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", views.password_reset_done, name="password_reset_done"),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        views.password_reset_complete,
        name="password_reset_complete",
    ),
]

online/website/urls.py
from django.urls import path

from . import views

"""
Основные маршруты приложения website.
"""

app_name = "website"
urlpatterns = [
    path("", views.index, name="index"),
    path("profile", views.profile, name="profile"),
    path("profile_edit", views.profile_edit, name="profile_edit"),
    path("service", views.service_view, name="service"),
    path("contact", views.contact, name="contact"),
    path("service/<int:pk>", views.service_info, name="service_info"),
    path("comment", views.comments, name="comment"),
    path("comment_add", views.comment_add, name="comment_add"),
    path(
        "comment/<int:pk>/update",
        views.CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "comment/<int:pk>/delete",
        views.CommentDeleteView.as_view(),
        name="comment-delete",
    ),
    path("gallery", views.gallery, name="photo-gallery"),
]

online/booking/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from website.models import Service

from .constant import TIMES

TIME_CHOICES = [(x, x) for x in TIMES]


class Appointment(models.Model):
    """
    Модель записи времени
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, null=True, blank=True
    )
    day = models.DateField(default=datetime.now)
    time = models.CharField(max_length=40, choices=TIME_CHOICES, default="12.00")
    time_ordered = models.DateTimeField(default=datetime.now, blank=True)


class HistoryBooking(models.Model):
    """
    Модель истории записи
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, null=True, blank=True
    )
    day = models.DateField(default=datetime.now)
    time = models.CharField(max_length=10, choices=TIME_CHOICES, default="3 PM")
    time_ordered = models.DateTimeField(default=datetime.now, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} | day: {self.day} | time: {self.time} | {self.service}"


class BookingSettings(models.Model):
    """
    Модель выбора времени работ мастера
    """

    start_time = models.DateField(default=datetime.now)
    end_time = models.DateField()

    def clean(self):
        """
        Валидация на правильный выбор данных
        """

        if self.start_time >= self.end_time:
            raise ValidationError("Start_time не должен быть равен или больше End_time")

online/booking/views.py
from datetime import datetime, time, timedelta

from django.contrib import messages
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from dotenv import load_dotenv

from .constant import TIMES
from .models import *
from .tasks import notifacation_record

load_dotenv()


def booking(request: HttpRequest) -> HttpResponse:
    """
    Отображает страницу выбора услуги и делается запрос в БД  service для отображения услуг
    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со страницей выбора услуги
    """
    services = Service.objects.all()
    if request.method == "POST":
        service = request.POST.get("service")
        if service is None:
            messages.success(request, "Выберите услугу")
            return redirect(reverse("booking:booking"))
        request.session["service"] = service  # присвоение значения service в сессию
        return redirect(reverse("booking:booking_day"))

    return render(request, "booking/booking.html", {"services": services})


def booking_day(request: HttpRequest, service_id: int = None) -> HttpResponse:
    """
    Отображает страницу выбора дня для бронирования услуги.

    Args:
    - request: объект HttpRequest, содержащий информацию о запросе, который вызывает функцию.
    - service_id: необязательный целочисленный параметр, содержащий идентификатор услуги, выбранной пользователем.

    Return: объект HttpResponse с отображением шаблона booking/booking_day.html с контекстом,
    содержащим список дней и информацию о том, являются ли эти дни доступными для бронирования.
    """
    weekdays = validweekday(31)
    services = Service.objects.all()
    validate_weekdays = isweekdayvalid(weekdays)
    if service_id is not None:
        service = Service.objects.get(id=service_id)
        request.session["service"] = service.name
    if request.method == "POST":
        day = request.POST.get("day")
        request.session["day"] = day
        return redirect(reverse("booking:bookingSubmit"))

    return render(
        request,
        "booking/booking_day.html",
        {
            "weekdays": weekdays,
            "validateWeekdays": validate_weekdays,
            "services": services,
        },
    )


def bookingsubmit(request: HttpRequest) -> HttpResponse:
    """
    Отображает страницу выбора времени записи для клиента
    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со временем записи для клиента
    """
    services = Service.objects.all()
    day = request.session.get("day")
    service_name = request.session.get("service")
    service = Service.objects.get(name=service_name) if service_name else None
    hour = checktime(
        TIMES, day
    )  # проверка забронировано ли время другим пользователем в этот день
    time = request.POST.get("time")  # получение времени
    if (
            request.method == "POST"
            and (
            Appointment.objects.filter(day=day, time=time).count() < 1
            and Appointment.objects.filter(day=day).count() < 11
    )
    ):
        record = Appointment.objects.get_or_create(
            user=request.user,
            service=service,
            day=day,
            time=time,
        )
        appoint_id = record[0].id
        notifacation_record.delay(appoint_id)
        messages.success(request, "Appointment already exists!")
        return redirect("booking:user_record")
    return render(
        request,
        "booking/bookingSubmit.html",
        {"times": hour, "services": services},
    )


def userupdate(request: HttpRequest, id: int) -> HttpResponse:
    """
    Обрабатывает запрос на обновление записи клиента,клиент заново выбирает день и услугу и передает id дальше.

    Args:
    - request: объект запроса Django HttpRequest
    - id: идентификатор записи, которую нужно обновить

    Returns: HttpResponse объект, который содержит HTML-страницу с формой обновления времени и услуги.
    """
    services = Service.objects.all()
    appointment = Appointment.objects.get(pk=id)
    userdatepicked = appointment.day
    # Copy  booking:
    today = datetime.today()

    # 24h if statement in template:
    delta24 = userdatepicked.strftime("%Y-%m-%d") >= (
            today + timedelta(days=1)
    ).strftime("%Y-%m-%d")
    # Calling 'validWeekday' Function to Loop days you want in the next 21 days:
    weekdays = validweekday(31)

    # Only show the days that are not full:
    validateweekdays = isweekdayvalid(weekdays)
    if delta24 is True:
        if request.method == "POST":
            service = request.POST.get("service")
            day = request.POST.get("day")

            # Store day and service in django session:
            request.session["day"] = day
            request.session["service"] = service

            return redirect(reverse("booking:userUpdateSubmit", args=[id]))
        return render(
            request,
            "booking/userUpdate.html",
            {
                "weekdays": weekdays,
                "validateWeekdays": validateweekdays,
                "delta24": delta24,
                "id": id,
                "services": services,
            },
        )
    else:
        return render(request, "booking/falsedelete.html")


def userupdatesubmit(request: HttpRequest, id: int) -> HttpResponse:
    """
    Обрабатывает запрос на обновление записи клиента, клиент выбирает новое время записи.

    Args:
    - request: объект запроса Django HttpRequest
    - id: идентификатор записи, которую нужно обновить

    Returns: HttpResponse объект, который содержит HTML-страницу с формой обновления времени записи.
    """
    services = Service.objects.all()
    day = request.session.get("day")
    service_name = request.session.get("service")
    service = Service.objects.get(name=service_name) if service_name else None
    hour = checktime(TIMES, day)
    appointment = Appointment.objects.get(pk=id)
    userselectedtime = appointment.time
    if request.method == "POST":
        time = request.POST.get("time")
        if Appointment.objects.filter(day=day).count() < 11:
            if (
                    Appointment.objects.filter(day=day, time=time).count() < 1
                    or userselectedtime == time
            ):
                Appointment.objects.filter(pk=id).update(
                    user=request.user,
                    service=service,
                    day=day,
                    time=time,
                )
                messages.success(request, "Appointment Edited!")
                return redirect("booking:user_record")
    return render(
        request,
        "booking/userUpdateSubmit.html",
        {
            "times": hour,
            "id": id,
            "services": services,
        },
    )


def validweekday(days: int) -> list:
    """
    Возвращает список дат, на которые можно записаться на прием в течение следующих дней.

    Args:
    - days (int): количество дней, на которые нужно вернуть список дат.

    Returns:
    - weekdays : список дат в формате 'YYYY-MM-DD'.
    """
    today = datetime.now()  # получение текущей даты
    weekdays = []  # пустой список для хранения для недели
    booking_settings = BookingSettings.objects.all()
    for i in range(days):
        for setting in booking_settings:
            x = today + timedelta(days=i)
            start_time = datetime.combine(setting.start_time, time.min)
            end_time = datetime.combine(setting.end_time, time.max)
            if start_time <= x <= end_time:
                weekdays.append(x.strftime("%Y-%m-%d"))
    return weekdays


def isweekdayvalid(x: list) -> list:
    """
    Возвращает список дат из списка x, на которые количество записей не превышает 10.

    Args:
    x (list): Список дат в формате YYYY-MM-DD.

    Returns:
    list: Список дат в формате YYYY-MM-DD, на которые количество записей не превышает 10.
    """
    validateweekdays = []
    for j in x:
        if Appointment.objects.filter(day=j).count() < 10:  # кол-во записей на день
            validateweekdays.append(j)
    return validateweekdays


def checktime(times: list, day: str) -> list:
    """
    Возвращает список доступный диапазон времени записи на сегодняшний день

    Args:
        times (list): Список всех возможных временных рамок.
        day (str): Строка с датой в формате 'YYYY-MM-DD'.

    Returns:
        list: Возвращает список доступный диапазон времени записи на сегодняшний день
    """
    x = []
    now = datetime.now()
    time = now.time()
    formatted_time = time.strftime("%H:%M")
    for k in times:
        if k > formatted_time and day == str(now.date()):
            if Appointment.objects.filter(day=day, time=k).count() < 1:
                x.append(k)
        elif day != str(now.date()):
            if Appointment.objects.filter(day=day, time=k).count() < 1:
                x.append(k)
    return x


def remove(request: HttpRequest, id: int) -> HttpResponse:
    """
    Удаляет запись на приём по переданному id.

    Args:
        request: объект запроса.
        id (int): id удаляемой записи.

    Returns:
        Если удаление прошло успешно, то происходит перенаправление на страницу
        со списком записей пользователя, иначе отображается страница с сообщением
        об ошибке удаления.
    """
    appointment = Appointment.objects.get(pk=id)
    userdatepicked = appointment.day
    today = datetime.today()
    delta24 = userdatepicked.strftime("%Y-%m-%d") >= (
            today + timedelta(days=1)
    ).strftime("%Y-%m-%d")
    if delta24 is True:
        appointment.delete()
        return redirect(reverse("booking:user_record"))
    else:
        return render(request, "booking/falsedelete.html")


def record_view(request: HttpRequest) -> HttpResponse:
    """

online/templates/Photogallery.html
{% extends "base.html"%}
{% load static %}
{% block content %}
<main>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center my-2">
                <h4>Фотогалерея</h4>
            </div>
        <div class="portfolio-menu mt-2 mb-4">
            <ul>
                <li class="btn btn-outline-dark active" data-filter="*">All</li>
                {% for photo in gallery_illu %}
                <li class="btn btn-outline-dark" data-filter=".{{ photo.category.name }}">{{ photo.category.name }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="portfolio-item row">
            {% for photo in gallery %}
            <div class="item {{photo.category.name}} col-lg-3 col-md-4 col-6 col-sm">
                <a href="{{photo.photo_gallery.url}}"
                   class="fancylight popup-btn" data-fancybox-group="light">
                    <img class="img-fluid"
                         src="{{photo.photo_gallery.url}}"
                         alt="">
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <script>
$('.portfolio-menu ul li').click(function(){
$('.portfolio-menu ul li').removeClass('active');
$(this).addClass('active');

var selector = $(this).attr('data-filter');
$('.portfolio-item').isotope({
    filter:selector
});
return  false;
});
$(document).ready(function() {
var popup_btn = $('.popup-btn');
popup_btn.magnificPopup({
type : 'image',
gallery : {
enabled : true
}
});
});





    </script>
</main>
{% endblock %}
{% include "footer.html" %}

online/templates/activate_email.html
{% autoescape off %} 
Hi {{ user.username }}, 
Please click on the link to confirm your registration, 
http://127.0.0.1:8000{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %} 

online/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block mainmenu %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock mainmenu %}
    {% block stylesheets %}
    {% endblock %}
</head>
<body>
{% block nav %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'website:index' %}"><span class="navbar-toggler-icon"></span></a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" href="#"></a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Услуги
                    </a>
                    <ul class="dropdown-menu">
                        {% for services in service %}
                        <li><a class="dropdown-item" href="{% url 'website:service_info' services.pk %}">{{ services.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'website:comment' %}">Отзывы</a></li>
                <li class="nav-item"><a class="nav-link active"
                                        href="{% url 'website:photo-gallery' %}">Фотогалерея</a></li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'website:service'%}">Цены</a></li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'website:contact'%}">Контакты</a></li>
            </ul>
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Профиль
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'website:profile' %}">{{user.username}}</a></li>
                        <li><a class="dropdown-item" href="{% url 'booking:user_record' %}">Записи</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:password-change' %}">Изменить пароль</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'users:logout' %}">Выйти</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link active" href="{% url 'users:register' %}">Регистрация</a></li>

                <li class="nav-item"><a class="nav-link active" href="{% url 'users:login' %}">Войти</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<section class="main">
{% block content %}
{% endblock %}
</section>
<footer>
    {% include "footer.html" %}
</footer>
</body>
</html>

online/templates/booking.html
<title>Online Booking</title>
{% load static %}
{% block body %}




{% if user.is_authenticated %}
<h1 class="text-center  mt-3">Online Booking</h1>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <form method="post" action="{% url 'booking:booking' %}" class="me-2 ms-2">
        {% csrf_token %}

        <!--input service-->
        <div>
            <h3 class="">Select Service:</h3>
            <select class="form-select fs-3" name="service">
                {% for service in services %}
                    <option value="{{service}}">{{service}}</option>
                {% endfor %}
            </select>
        </div>
            <!--input day-->
            <div class="mt-3">
                <h3 class="">Select Day:</h3>
                <select class="form-select fs-3" name="day">
                    {% for validateWeekday in validateWeekdays %}
                    <option value="{{validateWeekday}}">{{validateWeekday}}</option>
                    {% endfor %}
                </select>
            </div>

            <br/>
            <button type="submit" class="btn btn-primary text-white">Continue</button>
    </form>
</div>

{% else %}

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <h1 class="p-2  me-3">You Are Not Signed in!</h1>
    <a href="{% url 'users:register' %}" class="btn btn-primary shadow text-center">Sign in</a>
</div>

{% endif %}


{% endblock %}

online/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Контакты</h2>
            <li><a href="https://www.google.com/maps?q=Минск+Пушкина+1">Минск, ул. Пушкина, 1</a></li>
            <li>пн-пт: 10:00 - 18:00</li>
            <li>без перерыва</li>
            <li><a href="tel:5551234567">555 123-45-67</a></li>
            <li><a href="tel:5551234568">555 123-45-68</a></li>
            <li><a href="tel:5551234569">555 123-45-69</a></li>
            <li><i class="fa fa-cart-arrow-down" aria-hidden="true" font-size="16px" ></i>  Оплата: наличными </li>
        </div>
    </div>
    <hr>
</div>
{% endblock %}

{% include "footer.html" %}

online/templates/footer.html
<footer>
		<section class="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-3 col-6">
						<h4>Информация</h4>
						<ul class="list-unstyled">
							<li><a href="{% url 'website:index'%}">Главная</a></li>
							<li><a href="#">Контакты</a></li>
						</ul>
					</div>

					<div class="col-md-3 col-6">
						<h4>Время работы</h4>
						<ul class="list-unstyled">
							<li><a href="https://www.google.com/maps?q=Минск+Пушкина+1">Минск, ул. Пушкина, 1</a></li>
							<li>пн-пт: 10:00 - 18:00</li>
							<li>без перерыва</li>
						</ul>
					</div>

					<div class="col-md-3 col-6">
						<h4>Контакты</h4>
						<ul class="list-unstyled">
							<li><a href="tel:5551234567">555 123-45-67</a></li>
							<li><a href="tel:5551234568">555 123-45-68</a></li>
							<li><a href="tel:5551234569">555 123-45-69</a></li>
						</ul>
					</div>

					<div class="col-md-3 col-6">
						<h4>Мы в сети</h4>
						<div class="footer-icons">
							<a href="#"><i class="fab fa-facebook-f"></i></a>
							<a href="#"><i class="fab fa-youtube"></i></a>
							<a href="#"><i class="fab fa-instagram"></i></a>
						</div>
					</div>
				</div>
			</div>
		</section>
	</footer>

online/templates/main.html
{% extends "base.html"%}
{% load static %}
{% block content %}
<section class="service-section py-5">
    <div class="container text-center">
        <div class="service-details mb-4">
            <div class="row">
                <h1 class="display-4 font-weight-bold">Приветствую вас на моей странице!</h1>
                <p class="lead">
                    Я - Лера, мастер по тейпированию. Если у вас болит спина, шея или другая часть тела, я могу помочь
                    вам решить эту проблему. С помощью специальных тейпов я могу снять напряжение в мышцах и улучшить
                    кровообращение.
                    Тейпирование - это безболезненный и эффективный метод, который уже помог многим моим клиентам. Тейпы
                    устраняют боли и спазмы мышц, помогают восстановить суставы и связки, а также улучшают лимфодренаж.
                    Я с радостью помогу и вам!
                </p>
                <a class="btn btn-primary btn-lg mt-4" href="{% url 'booking:booking'%}" role="button">Записаться на
                    услугу</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% include "footer.html" %}

online/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<main class="container mt-5">
    <div class="row">
        {% if not profile %}
        <div class="col-md-6 mx-auto">
            <h2 class="mb-4">Создание профиля</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="{{ form.first_name.id_for_label }}" class="form-label">Введите имя</label>
                    {{ form.first_name }}
                </div>
                <div class="mb-3">
                    <label for="{{ form.last_name.id_for_label }}" class="form-label">Введите фамилию</label>
                    {{ form.last_name }}
                </div>
                <div class="mb-3">
                    <label for="profile-image" class="form-label">Выберите аватар профиля</label>
                    <input class="form-control" type="file" name="profile_image" id="profile-image">
                </div>
                <div class="mb-3">
                    <label for="{{ form.phone_number.id_for_label }}" class="form-label">Телефонный номер</label>
                    {{ form.phone_number }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        </div>
    </div>
    {% endif %}
</main>
<div class="wrapper">
    {% for profiles in profile %}
    <div class="profile" style="background-image: url({{ profiles.profile_image.url }}); background-size: contain; background-repeat: no-repeat; background-position: top;">
        <div class="overlay">
            <div class="about d-flex flex-column">
                <h4>{{ profiles.first_name }} {{ profiles.last_name }}</h4> <span>Номер телефона: {{ profiles.phone_number }}</span>
            </div>
            <ul class="social-icons">
                <a style="text-decoration: none" href="{% url 'booking:booking'%}"><li>Записаться</li></a>
                <a href ="{% url 'booking:user_record' %}" style="text-decoration: none"><li>Ваши записи</li></a>
                <a href ="{% url 'booking:history_user' %}" style="text-decoration: none"><li>История записей</li></a>
            </ul>
            <ul class="social-icons-custom">
                <a href ="{% url 'website:profile_edit' %}" style="text-decoration: none"><li>Редактировать профиль</li></a>
            </ul>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}
{% include "footer.html" %}

online/templates/service.html
{% extends "base.html"%}
{% load static %}
{% block content %}
<section class="articles-cost">
  {% for services in service %}
  <article>
    <div class="article-wrapper-cost">
      <div class="avatar-wrapper">
        <img src="{{ services.service_image.url }}" alt="" class="avatar" />
      </div>
      <div class="article-body-cost">
        <h2 class="article-h2">{{ services.name }}</h2>
        <p class="article-p">{{ services.short_description }}</p>
        <div class="service-info">
          <span class="service-price">{{ services.cost }} Бел.руб</span>
        </div>
        <div class="service-info-a">
          <a href="{% url 'website:service_info' services.id %}" class="read-more-cost">
            Подробнее
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </a>
        </div>
      </div>
    </div>
  </article>
  {% endfor %}
</section>
{% endblock %}
{% include "footer.html" %}