online/booking/urls.py
from django.urls import path

from . import views

"""
Основные маршруты приложения booking.
"""

app_name = "booking"
urlpatterns = [
    path("booking", views.booking, name="booking"),
    path("booking_day", views.booking_day, name="booking_day"),
    path("booking_day/<int:service_id>", views.booking_day, name="booking_day"),
    path("booking-submit", views.bookingsubmit, name="bookingSubmit"),
    path("user-update/<int:id>", views.userupdate, name="userUpdate"),
    path(
        "user-update-submit/<int:id>", views.userupdatesubmit, name="userUpdateSubmit"
    ),
    path("remove/<int:id>", views.remove, name="remove"),
    path("user_record", views.record_view, name="user_record"),
    path("history", views.history_user, name="history_user"),
]

online/online/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("website/", include("website.urls")),
                  path("users/", include("users.urls")),
                  path("booking/", include("booking.urls")),
                  path("__debug__/", include("debug_toolbar.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online/users/urls.py
from django.urls import path

from . import views
from .views import MyPasswordResetView, PasswordResetConfirmView

"""
Основные маршруты приложения users.
"""

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("password-change/", views.password_change, name="password-change"),
    path("activate/<str:uidb64>/<str:token>/", views.activate, name="activate"),
    path("password_reset/", MyPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", views.password_reset_done, name="password_reset_done"),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        views.password_reset_complete,
        name="password_reset_complete",
    ),
]

online/booking/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from website.models import Service

from .constant import TIMES

TIME_CHOICES = [(x, x) for x in TIMES]


class Appointment(models.Model):
    """
    Модель записи времени
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, null=True, blank=True
    )
    day = models.DateField(default=datetime.now)
    time = models.CharField(max_length=40, choices=TIME_CHOICES, default="12.00")
    time_ordered = models.DateTimeField(default=datetime.now, blank=True)


class HistoryBooking(models.Model):
    """
    Модель истории записи
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, null=True, blank=True
    )
    day = models.DateField(default=datetime.now)
    time = models.CharField(max_length=10, choices=TIME_CHOICES, default="3 PM")
    time_ordered = models.DateTimeField(default=datetime.now, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} | day: {self.day} | time: {self.time} | {self.service}"


class BookingSettings(models.Model):
    """
    Модель выбора времени работ мастера
    """

    start_time = models.DateField(default=datetime.now)
    end_time = models.DateField()

    def clean(self):
        """
        Валидация на правильный выбор данных
        """

        if self.start_time >= self.end_time:
            raise ValidationError("Start_time не должен быть равен или больше End_time")

online/booking/views.py
from datetime import datetime, time, timedelta

from django.contrib import messages
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from dotenv import load_dotenv

from .constant import TIMES
from .models import *
from .tasks import notifacation_record

load_dotenv()


def booking(request: HttpRequest) -> HttpResponse:
    """
    Отображает страницу выбора услуги и делается запрос в БД  service для отображения услуг
    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со страницей выбора услуги
    """
    services = Service.objects.all()
    if request.method == "POST":
        service = request.POST.get("service")
        if service is None:
            messages.success(request, "Выберите услугу")
            return redirect(reverse("booking:booking"))
        request.session["service"] = service  # присвоение значения service в сессию
        return redirect(reverse("booking:booking_day"))

    return render(request, "booking/booking.html", {"services": services})


def booking_day(request: HttpRequest, service_id: int = None) -> HttpResponse:
    """
    Отображает страницу выбора дня для бронирования услуги.

    Args:
    - request: объект HttpRequest, содержащий информацию о запросе, который вызывает функцию.
    - service_id: необязательный целочисленный параметр, содержащий идентификатор услуги, выбранной пользователем.

    Return: объект HttpResponse с отображением шаблона booking/booking_day.html с контекстом,
    содержащим список дней и информацию о том, являются ли эти дни доступными для бронирования.
    """
    weekdays = validweekday(31)
    services = Service.objects.all()
    validate_weekdays = isweekdayvalid(weekdays)
    if service_id is not None:
        service = Service.objects.get(id=service_id)
        request.session["service"] = service.name
    if request.method == "POST":
        day = request.POST.get("day")
        request.session["day"] = day
        return redirect(reverse("booking:bookingSubmit"))

    return render(
        request,
        "booking/booking_day.html",
        {
            "weekdays": weekdays,
            "validateWeekdays": validate_weekdays,
            "services": services,
        },
    )


def bookingsubmit(request: HttpRequest) -> HttpResponse:
    """
    Отображает страницу выбора времени записи для клиента
    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со временем записи для клиента
    """
    services = Service.objects.all()
    day = request.session.get("day")
    service_name = request.session.get("service")
    service = Service.objects.get(name=service_name) if service_name else None
    hour = checktime(
        TIMES, day
    )  # проверка забронировано ли время другим пользователем в этот день
    time = request.POST.get("time")  # получение времени
    if (
            request.method == "POST"
            and (
            Appointment.objects.filter(day=day, time=time).count() < 1
            and Appointment.objects.filter(day=day).count() < 11
    )
    ):
        record = Appointment.objects.get_or_create(
            user=request.user,
            service=service,
            day=day,
            time=time,
        )
        appoint_id = record[0].id
        notifacation_record.delay(appoint_id)
        messages.success(request, "Appointment already exists!")
        return redirect("booking:user_record")
    return render(
        request,
        "booking/bookingSubmit.html",
        {"times": hour, "services": services},
    )


def userupdate(request: HttpRequest, id: int) -> HttpResponse:
    """
    Обрабатывает запрос на обновление записи клиента,клиент заново выбирает день и услугу и передает id дальше.

    Args:
    - request: объект запроса Django HttpRequest
    - id: идентификатор записи, которую нужно обновить

    Returns: HttpResponse объект, который содержит HTML-страницу с формой обновления времени и услуги.
    """
    services = Service.objects.all()
    appointment = Appointment.objects.get(pk=id)
    userdatepicked = appointment.day
    # Copy  booking:
    today = datetime.today()

    # 24h if statement in template:
    delta24 = userdatepicked.strftime("%Y-%m-%d") >= (
            today + timedelta(days=1)
    ).strftime("%Y-%m-%d")
    # Calling 'validWeekday' Function to Loop days you want in the next 21 days:
    weekdays = validweekday(31)

    # Only show the days that are not full:
    validateweekdays = isweekdayvalid(weekdays)
    if delta24 is True:
        if request.method == "POST":
            service = request.POST.get("service")
            day = request.POST.get("day")

            # Store day and service in django session:
            request.session["day"] = day
            request.session["service"] = service

            return redirect(reverse("booking:userUpdateSubmit", args=[id]))
        return render(
            request,
            "booking/userUpdate.html",
            {
                "weekdays": weekdays,
                "validateWeekdays": validateweekdays,
                "delta24": delta24,
                "id": id,
                "services": services,
            },
        )
    else:
        return render(request, "booking/falsedelete.html")


def userupdatesubmit(request: HttpRequest, id: int) -> HttpResponse:
    """
    Обрабатывает запрос на обновление записи клиента, клиент выбирает новое время записи.

    Args:
    - request: объект запроса Django HttpRequest
    - id: идентификатор записи, которую нужно обновить

    Returns: HttpResponse объект, который содержит HTML-страницу с формой обновления времени записи.
    """
    services = Service.objects.all()
    day = request.session.get("day")
    service_name = request.session.get("service")
    service = Service.objects.get(name=service_name) if service_name else None
    hour = checktime(TIMES, day)
    appointment = Appointment.objects.get(pk=id)
    userselectedtime = appointment.time
    if request.method == "POST":
        time = request.POST.get("time")
        if Appointment.objects.filter(day=day).count() < 11:
            if (
                    Appointment.objects.filter(day=day, time=time).count() < 1
                    or userselectedtime == time
            ):
                Appointment.objects.filter(pk=id).update(
                    user=request.user,
                    service=service,
                    day=day,
                    time=time,
                )
                messages.success(request, "Appointment Edited!")
                return redirect("booking:user_record")
    return render(
        request,
        "booking/userUpdateSubmit.html",
        {
            "times": hour,
            "id": id,
            "services": services,
        },
    )


def validweekday(days: int) -> list:
    """
    Возвращает список дат, на которые можно записаться на прием в течение следующих дней.

    Args:
    - days (int): количество дней, на которые нужно вернуть список дат.

    Returns:
    - weekdays : список дат в формате 'YYYY-MM-DD'.
    """
    today = datetime.now()  # получение текущей даты
    weekdays = []  # пустой список для хранения для недели
    booking_settings = BookingSettings.objects.all()
    for i in range(days):
        for setting in booking_settings:
            x = today + timedelta(days=i)
            start_time = datetime.combine(setting.start_time, time.min)
            end_time = datetime.combine(setting.end_time, time.max)
            if start_time <= x <= end_time:
                weekdays.append(x.strftime("%Y-%m-%d"))
    return weekdays


def isweekdayvalid(x: list) -> list:
    """
    Возвращает список дат из списка x, на которые количество записей не превышает 10.

    Args:
    x (list): Список дат в формате YYYY-MM-DD.

    Returns:
    list: Список дат в формате YYYY-MM-DD, на которые количество записей не превышает 10.
    """
    validateweekdays = []
    for j in x:
        if Appointment.objects.filter(day=j).count() < 10:  # кол-во записей на день
            validateweekdays.append(j)
    return validateweekdays


def checktime(times: list, day: str) -> list:
    """
    Возвращает список доступный диапазон времени записи на сегодняшний день

    Args:
        times (list): Список всех возможных временных рамок.
        day (str): Строка с датой в формате 'YYYY-MM-DD'.

    Returns:
        list: Возвращает список доступный диапазон времени записи на сегодняшний день
    """
    x = []
    now = datetime.now()
    time = now.time()
    formatted_time = time.strftime("%H:%M")
    for k in times:
        if k > formatted_time and day == str(now.date()):
            if Appointment.objects.filter(day=day, time=k).count() < 1:
                x.append(k)
        elif day != str(now.date()):
            if Appointment.objects.filter(day=day, time=k).count() < 1:
                x.append(k)
    return x


def remove(request: HttpRequest, id: int) -> HttpResponse:
    """
    Удаляет запись на приём по переданному id.

    Args:
        request: объект запроса.
        id (int): id удаляемой записи.

    Returns:
        Если удаление прошло успешно, то происходит перенаправление на страницу
        со списком записей пользователя, иначе отображается страница с сообщением
        об ошибке удаления.
    """
    appointment = Appointment.objects.get(pk=id)
    userdatepicked = appointment.day
    today = datetime.today()
    delta24 = userdatepicked.strftime("%Y-%m-%d") >= (
            today + timedelta(days=1)
    ).strftime("%Y-%m-%d")
    if delta24 is True:
        appointment.delete()
        return redirect(reverse("booking:user_record"))
    else:
        return render(request, "booking/falsedelete.html")


def record_view(request: HttpRequest) -> HttpResponse:
    """

online/booking/templates/booking/booking.html
{% extends "base.html"%}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<h1 class="text-center  mt-3">Онлайн запись</h1>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <form method="post" action="{% url 'booking:booking' %}" class="me-2 ms-2">
        {% csrf_token %}
        <!--input service-->
        <div>
            <h3 class="">Выбери услугу:</h3>
            <select class="form-select" name="service">
                {% for service in services %}
                    <option value="{{service}}">{{service}}</option>
                {% endfor %}
            </select>
        </div>
            <br/>
            <button type="submit" class="btn btn-primary text-white">Продолжить</button>
    </form>
</div>
{% endif %}
{% endblock %}

online/booking/templates/booking/bookingSubmit.html
{% extends "base.html"%}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<h1 class="text-center fPersian mt-3">Онлайн запись</h1>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black text-center m-5">
    <form method="post" action="{% url 'booking:bookingSubmit' %}" class="me-2 ms-2" required>
        {% csrf_token %}

        <!--input time-->
        <h3 class="text-center fPersian mt-4">Выберите время:</h3>
        <div>
            <select class="form-select text-center" name="time">
                {% for time in times %}
                <option value="{{time}}">{{time}}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary text-white mt-3 fPersian">Записаться</button>

    </form>
</div>

{% endif %}

{% endblock %}

online/booking/templates/booking/booking_day.html
{% extends "base.html"%}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<h1 class="text-center  mt-3">Онлайн запись</h1>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <form method="post" action="{% url 'booking:booking_day' %}" class="me-2 ms-2">
        {% csrf_token %}
            <!--input day-->
            <div class="mt-3">
                <h3 class="">Выберите день:</h3>
                <select class="form-select" name="day">
                    {% for validateWeekday in validateWeekdays %}
                    <option value="{{validateWeekday}}">{{validateWeekday}}</option>
                    {% endfor %}
                </select>
            </div>

            <br/>
            <button type="submit" class="btn btn-primary text-white">Продолжить</button>
    </form>
</div>
{% endif %}
{% endblock %}

online/booking/templates/booking/falsedelete.html
{% extends "base.html"%}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black m-5 text-center fPersian">
    <h1 class="text-danger">Нельзя изменить или удалить время записи, в день записи, пожалуйста отпишите Мастеру!</h1>
    <a href="{% url 'booking:user_record' %}" class="btn btn-primary mt-5">Вернуться в ваши записи</a>
</div>
{% endif %}
{% endblock %}

online/booking/templates/booking/history_user.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="text-center mb-5">История ваших заказов</h3>
    </div>
  </div>
  <div class="row align-items-stretch">
    {% for history in history_user %}
    <div class="col-md-4 mb-5">
      <div class="card p-3 h-100">
        <div class="row">
          <div class="col-4">
            <p class="history-label mb-0">Услуга:</p>
          </div>
          <div class="col-8">
            <p class="history-value mb-0">{{ history.service }}</p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p class="history-label mb-0">День:</p>
          </div>
          <div class="col-8">
            <p class="history-value mb-0">{{ history.day }}</p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p class="history-label mb-0">Время:</p>
          </div>
          <div class="col-8">
            <p class="history-value mb-0">{{ history.time }}</p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

{% include "footer.html" %}

online/booking/templates/booking/userUpdate.html
{% extends "base.html"%}
{% load static %}
{% block content %}
{% if user.is_authenticated %}

<h1 class="text-center  mt-3">Редактирование записи</h1>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <form method="post" action="{% url 'booking:userUpdate' id %}" class="me-2 ms-2" required>
        {% csrf_token %}

        <!--input service-->
        <div>
            <h3 class="">Выберите услугу:</h3>
            <select class="form-select" name="service">
                {% for service in services %}
                    <option value="{{service}}">{{service}}</option>
                {% endfor %}
            </select>
        </div>
            <!--input day-->
            <div class="mt-3">
                <h3 class="">Выберите день:</h3>
                <select class="form-select" name="day">
                    {% for validateWeekday in validateWeekdays %}
                    <option value="{{validateWeekday}}">{{validateWeekday}}</option>
                    {% endfor %}
                </select>
            </div>

            <br/>
            <button type="submit" class="btn btn-primary text-white">Продолжить</button>
    </form>
</div>
{% endif %}
{% endblock %}

online/booking/templates/booking/userUpdateSubmit.html
{% extends "base.html"%}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<h1 class="text-center fPersian mt-3">Редактирование записи</h1>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black text-center m-5">
    <form method="post" action="{% url 'booking:userUpdateSubmit' id %}" class="me-2 ms-2" required>
        {% csrf_token %}

        <!--input time-->
        <h3 class="text-center fPersian mt-4">Выберите время:</h3>
        <div>
            <select class="form-select text-center" name="time">
                {% for time in times %}
                <option value="{{time}}">{{time}}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary text-white mt-3 fPersian">Записаться</button>

    </form>
</div>
{% endif %}
{% endblock %}

online/booking/templates/booking/user_record.html
{% extends "base.html"%}
{% load static %}
{% block content %}
<h1 class="custom">Ваши записи</h1>
{% if appointments.count > 0 %}
<div class="my_div">
    <div class="my_div-custom">
        {% for appointment in appointments %}
        <div class="list-group-custom">
            <p class="list-group-custom item">День: {{ appointment.day }}</p>
            <p class="list-group-custom item">Время: {{ appointment.time }}</p>
            <p class="list-group-custom item">Услуга: {{ appointment.service.name }}</p>
            <div class="mt-3 mb-2">
                <a class="btn btn-primary rounded-3 p-2" href="{% url 'booking:userUpdate' appointment.id %}">Редактировать запись</a>
                <a class="btn btn-primary rounded-3 p-2" href="{% url 'booking:remove' appointment.id %}">Удалить запись</a>
            </div>
        </div>
        <hr>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}