online/online/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("website/", include("website.urls")),
                  path("users/", include("users.urls")),
                  path("booking/", include("booking.urls")),
                  path("__debug__/", include("debug_toolbar.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online/users/urls.py
from django.urls import path

from . import views
from .views import MyPasswordResetView, PasswordResetConfirmView

"""
Основные маршруты приложения users.
"""

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("password-change/", views.password_change, name="password-change"),
    path("activate/<str:uidb64>/<str:token>/", views.activate, name="activate"),
    path("password_reset/", MyPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", views.password_reset_done, name="password_reset_done"),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        views.password_reset_complete,
        name="password_reset_complete",
    ),
]

online/website/urls.py
from django.urls import path

from . import views

"""
Основные маршруты приложения website.
"""

app_name = "website"
urlpatterns = [
    path("", views.index, name="index"),
    path("profile", views.profile, name="profile"),
    path("profile_edit", views.profile_edit, name="profile_edit"),
    path("service", views.service_view, name="service"),
    path("contact", views.contact, name="contact"),
    path("service/<int:pk>", views.service_info, name="service_info"),
    path("comment", views.comments, name="comment"),
    path("comment_add", views.comment_add, name="comment_add"),
    path(
        "comment/<int:pk>/update",
        views.CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "comment/<int:pk>/delete",
        views.CommentDeleteView.as_view(),
        name="comment-delete",
    ),
    path("gallery", views.gallery, name="photo-gallery"),
]

online/website/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Service(models.Model):
    """
    Модель услуг которые предоставляет мастер
    """

    name = models.CharField(max_length=50, verbose_name="Название услуги")
    description = models.TextField(max_length=1000, verbose_name="Описание услуги")
    cost = models.IntegerField()
    service_image = models.ImageField(
        upload_to="service_image", blank=True, null=True, verbose_name="Service Image"
    )
    pros = models.TextField(max_length=1000, verbose_name="Описание плюсов")
    minuses = models.TextField(max_length=1000, verbose_name="Описание минусов")
    short_description = models.TextField(
        max_length=250, verbose_name="Короткое описание"
    )
    time = models.CharField(
        max_length=40, verbose_name="Длительность услуги", default="15 минут"
    )
    slug = models.CharField(
        max_length=50, verbose_name="Сокращенное название услуги", default=""
    )

    def __str__(self):
        """
        строковое представление объектов Service
        """
        return self.name


class Profile(models.Model):
    """
    Модель профиля для пользователя
    """

    first_name = models.CharField(max_length=25, verbose_name="Имя пользователя")
    last_name = models.CharField(max_length=25, verbose_name="Фамилия пользователя")
    profile_image = models.ImageField(
        upload_to="profile", blank=True, null=True, verbose_name="Profile Image"
    )
    phone_number = models.CharField(
        max_length=20, verbose_name="Номер телефона пользователя"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        """
        строковое представление объектов Profile
        """
        return self.first_name


class CommentWebsite(models.Model):
    """
    Модель отзывов о мастере
    """

    text = models.TextField(max_length=250, verbose_name="Comment text")
    pub_date = models.DateField(verbose_name="Comment publication date", auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    update_date = models.DateField(verbose_name="Comment update date", auto_now=True)

    @staticmethod
    def get_absolute_url():
        """
        При совершении действий возвращает по пути указанной в reverse
        """
        return reverse("website:comment")


class PhotoGallery(models.Model):
    """
    Модель фотогалереи вебсайта
    """

    photo_gallery = models.ImageField(
        upload_to="profile", blank=True, null=True, verbose_name="Photo gallery Image"
    )
    category = models.ForeignKey(
        Service, on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        """
        Добавил индексы для поле таблицы photo_gallery
        """

        indexes = [
            models.Index(fields=["photo_gallery"], name="website_photo_gallery-index"),
        ]

online/website/forms.py
from django import forms
from django.forms import Textarea

from .models import CommentWebsite, Profile


class ProfileModelForm(forms.ModelForm):
    """
    Форма для ввода данных профиля
    """

    profile_image = forms.ImageField(label="Фото профиля", required=False)

    class Meta:
        model = Profile
        fields = ["first_name", "last_name", "profile_image", "phone_number"]
        widgets = {
            "first_name": forms.TextInput(
                attrs={"class": "custom-class", "placeholder": "Введите имя"}
            ),
            "last_name": forms.TextInput(
                attrs={"class": "custom-class", "placeholder": "Введите фамилию"}
            ),
            "phone_number": forms.TextInput(
                attrs={"class": "custom-class", "placeholder": "Введите номер телефона"}
            ),
        }
        labels = {
            "first_name": "Имя",
            "last_name": "Фамилия",
            "number_phone": "Мобильный номер",
        }


class CommentModelForm(forms.ModelForm):
    """
    Форма для ввода и редактирования комментария
    """

    class Meta:
        model = CommentWebsite
        exclude = [
            "pub_date",
            "update_date",
            "user",
        ]
        widgets = ({"text": Textarea(attrs={"cols": 80, "rows": 20})},)
        labels = (
            {
                "text": "Оставьте ваш отзыв",
            },
        )
        help_texts = {"text": "Оцените нас,пожалуйста "}
        fields = ("text",)
        required = {"rating": False}


class ProfileEditModelForm(forms.ModelForm):
    """
    Форма для редактирования профиля
    """

    profile_image = forms.ImageField(label="Фото профиля", required=False)

    class Meta:
        model = Profile
        fields = ["first_name", "last_name", "profile_image", "phone_number"]
        widgets = {
            "first_name": forms.TextInput(
                attrs={"class": "custom-class", "placeholder": "Введите имя"}
            ),
            "last_name": forms.TextInput(
                attrs={"class": "custom-class", "placeholder": "Введите фамилию"}
            ),
            "phone_number": forms.TextInput(
                attrs={"class": "custom-class", "placeholder": "Введите номер телефона"}
            ),
        }
        labels = {
            "first_name": "Имя",
            "last_name": "Фамилия",
            "number_phone": "Мобильный номер",
        }

online/website/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic.edit import DeleteView, UpdateView

from .forms import CommentModelForm, ProfileEditModelForm, ProfileModelForm
from .models import CommentWebsite, PhotoGallery, Profile, Service
from .tasks import replace_text_with_censored


def index(request: HttpRequest) -> HttpResponse:
    """
    Отображает главную страницу и делается запрос в БД для получения услуг service
    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP с главной страницей
    """
    service = Service.objects.all()
    return render(request, "main.html", context={"service": service})


@login_required(login_url="users:login")
def profile(request: HttpRequest) -> HttpResponse:
    """
    Отображает профиль пользователя и форму для заполнения профиля если это требуется.
    Делается запрос в БД service для отображения услуг в шапке header и profile_all для получения всех
    всех данных пользователя
    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со страницей профиля пользователя и форму для заполнения профиля.
    """
    service = Service.objects.all()
    profile_all = Profile.objects.filter(user=request.user.id)
    if request.method == "POST":
        form = ProfileModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect(reverse("website:profile"))
    else:
        form = ProfileModelForm()
    return render(
        request,
        "profile.html",
        context={"profile": profile_all, "form": form, "service": service},
    )


@login_required(login_url="users:login")
def profile_edit(request: HttpRequest) -> HttpResponse:
    """
    Отображает страницу с формой для изменения профиля.
    Делается запрос в БД service для отображения услуг в шапке header и получения instance делается запрос в
    profile_user в БД
    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со страницей профиля пользователя
    """
    service = Service.objects.all()
    profile_user = Profile.objects.get(user=request.user.id)
    if request.method == "POST":
        form = ProfileEditModelForm(
            request.POST, request.FILES, instance=profile_user
        )  # передать текущий профиль в качестве экземпляра instance
        if form.is_valid():
            form.save()  # сохранить изменения
            return redirect(reverse("website:profile"))
    else:
        form = ProfileEditModelForm(instance=profile_user)
    return render(
        request,
        "profile_edit.html",
        context={"profile": profile_user, "form": form, "service": service},
    )


@login_required(login_url="users:login")
def service_view(request: HttpRequest) -> HttpResponse:
    """
    Отображает все услуги.
    Делается запрос в БД service для отображения услуг
    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со страницей всех услуг
    """
    service = Service.objects.all()
    return render(request, "service.html", context={"service": service})


@login_required(login_url="users:login")
def service_info(request, pk: int) -> HttpResponse:
    """
    Отображает информацию об услуге.

    Args:
        request (HttpRequest): объект запроса HTTP
        pk(int): Идентификатор услуги
    Returns:
        HttpResponse: объект ответа HTTP со страницей информации об услуге
        :param request:
        :param pk:
    """
    service = Service.objects.all()
    service_information = Service.objects.get(pk=pk)
    return render(
        request,
        "service_info.html",
        context={"service": service, "service_info": service_information},
    )


@login_required(login_url="users:login")
def comments(request: HttpRequest) -> HttpResponse:
    """
    Отображает все комментарии.

    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со страницей всех комментариев
    """
    service = Service.objects.all()
    comment_user = CommentWebsite.objects.filter(user=request.user)
    comment_another_users = CommentWebsite.objects.exclude(user=request.user)
    return render(
        request,
        "website/comment.html",
        context={
            "comment_user": comment_user,
            "comment_another_users": comment_another_users,
            "service": service,
        },
    )


@login_required(login_url="users:login")
def comment_add(request: HttpRequest) -> HttpResponse:
    """
    Отображает форму добавления комментария и подключен celery для фильтрации матов

    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со страницей формы добавления комментария
    """
    if request.method == "POST":
        comment_form = CommentModelForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            if request.user.is_authenticated:
                new_comment.user = request.user
            else:
                new_comment.user = None
                return redirect(reverse("users:login"))
            new_comment.save()
            replace_text_with_censored.delay(new_comment.id)
            return redirect(reverse("website:comment"))
    else:
        comment_form = CommentModelForm()
    return render(request, "website/comment_form.html", context={"form": comment_form})


class CommentUpdateView(UpdateView):
    """Представление для редактирования существующего комментария."""

    model = CommentWebsite
    form_class = CommentModelForm
    context_object_name = "comment"
    template_name_suffix = "_update"


class CommentDeleteView(DeleteView):
    """Представление для удаления существующего комментария."""

    model = CommentWebsite
    success_url = reverse_lazy("website:comment")
    context_object_name = "comment"
    template_name_suffix = "_delete"


@cache_page(259200)  # кэш на 3 дня
def gallery(request: HttpRequest) -> HttpResponse:
    """
    Отображает фотогалерею

    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP со страницей отображения фотогалереи
    """
    service = Service.objects.all()
    photo = PhotoGallery.objects.all()
    # код блока ниже для чего, добавляется дефиз, потому что в photogallery.html
    # есть data-filter, который не хочет высвечивать определенные фото с пробелом
    # поэтому приходится добавлять везде дефиз
    photo_illu = PhotoGallery.objects.all()
    category_names = set()
    new_photo_illu = []
    for i in photo_illu:
        category_name = i.category.slug
        if category_name not in category_names:
            category_names.add(category_name)
            i.category.slug = category_name
            new_photo_illu.append(i)
    photo_illu = new_photo_illu
    return render(
        request,
        "photogallery.html",
        context={"service": service, "gallery": photo_illu, "gallery_image": photo},
    )


def contact(request: HttpRequest) -> HttpResponse:
    """
    Отображает страницу контакты и делается запрос в БД для получения услуг service
    Args:
        request (HttpRequest): объект запроса HTTP

    Returns:
        HttpResponse: объект ответа HTTP страница контакты
    """
    service = Service.objects.all()
    return render(request, "contact.html", context={"service": service})

online/templates/website/comment.html
{% extends "base.html"%}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="container reviews">
    <div class="row">
        <div class="col text-center text-uppercase">
            <div class="title">
                <h2>Отзывы</h2>
            </div>
        </div>
    </div>
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            {% if comment_user %}
            <div class="carousel-item">
                <div class="row justify-content-center">
                    {% for comment in comment_user %}
                    <div class="col-md-3 col-sm-9 col-9">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Пользователь {{comment.user}}</h5>
                                <p class="card-text">{{comment.text}}</p>
                                <a class="btn btn-primary update-btn"
                                   href="{% url 'website:comment-update' pk=comment.pk %}">Редактировать отзыв</a>
                                <a class="btn btn-danger delete-btn"
                                   href="{% url 'website:comment-delete' pk=comment.pk %}">Удалить отзыв</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% for comments in comment_another_users %}
            {% if forloop.counter == 1 %}
            <div class="carousel-item active">
                <div class="row justify-content-center">
                    {% endif %}
                    <div class="col-md-3 col-sm-9 col-9">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Пользователь {{ comments.user }}</h5>
                                <p class="card-text">{{ comments.text }}</p>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:2 or forloop.last %}
                </div>
            </div>
            {% if not forloop.last %}
            <div class="carousel-item">
                <div class="row justify-content-center">
                    {% endif %}
                    {% endif %}
                    {% if forloop.last and not forloop.counter|divisibleby:3 %}
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </a>
    </div>
</div>
{% if comment_user.count < 1 %}
<div class="add-btn-container">
    <a class="btn btn-primary add-btn add-btn" href="{% url 'website:comment_add' %}">
        Добавить отзыв
    </a>
</div>
{% endif %}

<script>
    $(document).ready(function(){
        $('.carousel').carousel();
    });


</script>
{% endif %}
{% endblock %}
{% include "footer.html" %}

online/templates/website/comment_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container pink-bg">
  <h3 class="text-center mb-4">Напишите ваш отзыв</h3>
  <form method="post" class="comment-form">
    {% csrf_token %}
    <div class="form-group">
      <label>Ваш отзыв</label>
      {{form.text}}
    </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
  </form>
</div>
{% endblock %}
{% include "footer.html" %}

online/templates/website/commentwebsite_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="container-delete">
                <h3 class="text-center mb-4">Удаление комментария</h3>
                <div class="card-body text-center">
                  <div class="card-body-delete">
                      <p class="card-text-delete">Вы хотите удалить ваш комментарий?:</p><p class="delete">{{ comment.text }}</p>
                      <form action="" method="POST" class="comment-form">
                        {% csrf_token %}
                        <input class="btn btn-danger" type="submit" value="Yes, delete." />
                      </form>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% include "footer.html" %}
{% endblock %}

online/templates/website/commentwebsite_update.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container pink-bg">
  <h3 class="text-center mb-4">Напишите ваш отзыв</h3>
  <form method="post" class="comment-form">
    {% csrf_token %}
    <div class="form-group">
      <label>Ваш отзыв</label>
      {{form.text}}
    </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
  </form>
</div>
{% endblock %}
{% include "footer.html" %}